name: Tag and Push

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "select release semantic version"
        required: true
        type: choice
        options:
          - "patch"
          - "minor"
          - "major"

jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.18.x"
          registry-url: https://npm.pkg.github.com/
      - name: Git configuration
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
      - name: Bump version
        id: bump_version
        run: |
          VERSION_BUMP=${{ github.event.inputs.release_version }}
          NEW_VERSION=$(npm version $VERSION_BUMP --no-git-tag-version)
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"
          git tag $NEW_VERSION
      - name: Commit changes
        run: |
          git add package.json
          git commit -m "chore: Bump version to $NEW_VERSION"
      - name: Push Tag
        run: git push origin --atomic HEAD:${{ github.ref }} ${{ steps.bump_version.outputs.NEW_VERSION }}
